# Generated by Django 2.1.1 on 2020-05-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200531_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='time',
            field=models.DecimalField(decimal_places=0, default=1590910821.778305, max_digits=10000000000000),
        ),
    ]
